name: nubank
description: Nubank Clone

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  line_icons: ^0.2.0
  font_awesome_flutter: ^8.5.0
  flutter_svg: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/